CREATE VIEW REVENUE0 AS
 SELECT L_SUPPKEY AS SUPPLIER_NO, SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)) AS TOTAL_REVENUE
 FROM LINEITEM
 WHERE L_SHIPDATE >= '1996-01-01' AND L_SHIPDATE < '1996-04-01'
 GROUP BY L_SUPPKEY
